### ISSUE TITLE
breaks GitHub

### ISSUE THREAD

**Issue by haze2422** [uBlock-user/uBO-Personal-Filters#11]
*$3p,domain=github.com

![2020-05-05_153351](https://user-images.githubusercontent.com/15184981/81066625-0d996380-8ee6-11ea-9660-4f77622faa38.png)

**Comment by uBlock-user** [comment]
which version of uBO are you on ?

**Comment by haze2422** [comment]
Nano Adblocker v1.0.0.142 ( uBlock Origin Version/1.26.0 Commit/1295e25 )

**Comment by uBlock-user** [comment]
The filter is 

`*$3p,denyallow=githubassets.com|githubusercontent.com|s3.amazonaws.com|map.fastly.net,domain=github.com`

https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#denyallow

Nano hasn't implemented `denyallow` yet ?

**Comment by uBlock-user** [comment]
My filters are tested on uBO only, not on uBO's forks, so you will have to take it up with Nano's maintainer.

**Comment by gwarser** [comment]
It's broken in stable https://github.com/gorhill/uBlock/commit/36711a7c0761c6eecb8c7f7f9724cba6d1cc2994 https://github.com/gorhill/uBlock/commit/94935a4b9e5ff9d70eb6876c0214a570bab76371

**Comment by uBlock-user** [comment]
> It's broken in stable

Why ? || is not used, neither is a domain without ||

**Comment by gwarser** [comment]
It's not about `||`, it's about `*`/`|http://`/`|https://` with `domain=` option.

**Comment by haze2422** [comment]
uBO 1.26.0/1.26.2 - broken
uBO 1.26.3b20 - work

**Comment by uBlock-user** [comment]
Well I'm not waiting for the patch to land in stable, so disable it via `$badfilter` or however you see fit.
