### ISSUE TITLE
Could you reproduce this?

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Personal-Filters#12]
Platform = google chrome /opera browser
Ublock origin 1.26
**Ensure to use new ip and clear cookies/data**
Going here
`https://www5.watchmovie.movie/series/awoken-episode-0`

Click hamburger menu in ***video player itself*** { https://user-images.githubusercontent.com/20338483/81738481-6739f900-94b7-11ea-8abc-77b8d86081b4.jpg }

and not outside player

Select ***server hyrax***

***Wait for 20-35 sec*** ,antiadblock appears

https://user-images.githubusercontent.com/20338483/81507173-1ee4d480-9319-11ea-9eaa-f28f2bdf350d.png

Could you reproduce this?

I see this code in source page which is responsible
```
</script><script type=text/javascript>function setCookie(e,t,n){var o=new Date;o.setTime(o.getTime()+n);var r="expires="+o.toUTCString();document.cookie=e+"="+t+";"+r+";path=/"}function getCookie(e){for(var t=e+"=",n=document.cookie.split(";"),o=0;o<n.length;o++){for(var r=n[o];" "==r.charAt(0);)r=r.substring(1);if(0==r.indexOf(t))return r.substring(t.length,r.length)}return""}var isClick=!1,msgWebmaster='<center style="background:#00000054;margin:auto;width:100%;border-radius:0 0 5px 5px;padding:15px">\n            <h1>Hello Webmaster</h1>\n            <br/>\n            <h3>Please <span style="color:red">REMOVE SANDBOX</span> attribute <span style="color:red">IN IFRAME</span></h3>\n            <br/><br/>\n            <h1>Dear Visitor</h1>\n            <br/>\n            <h3>Please <span style="color:red">DISABLE ADBLOCK</span> extension or <span style="color:red">ALLOW POPUNDER</span> for this site.</h3>\n            <br/>\n            <h3>Video can\'t play if this page not show popunder.</h3>\n            <br/>\n            <h4>Thank you.</h4>\n        </center>',styleWebmaster="width:100%;height:100% !important;background: url(https://iamcdn.net/img/block-pop.jpg) center center no-repeat;background-size:contain;position:absolute",styleMinion="width:100%;height:100% !important;background: url(https://iamcdn.net/img/block.jpg) center center no-repeat;background-size:contain;position:absolute";$(document).ready(function(){$("#over").click(function(){html2canvas($("#player"),{onrendered:function(e){isClick=!0;var t=e.toDataURL("image/png"),n=window.open(t);n?($("#over").remove(),setCookie("over",!0,36e5)):("undefined"!=typeof jwplayer&&jwplayer&&jwplayer().remove(),$("#player").css("cssText",styleWebmaster).html(msgWebmaster)),n.focus(),n.close()}})}),setTimeout(function(){try{"undefined"!=typeof ADS&&"undefined"!=typeof html2canvas||$("#player").css("cssText",styleMinion).html("")}catch(e){$("#player").css("cssText",styleMinion).html("")}},5e3),setTimeout(function(){isClick||("undefined"!=typeof jwplayer&&jwplayer&&jwplayer().remove(),$("#player").css("cssText",styleWebmaster).html(msgWebmaster))},3e4)});var isCookie=getCookie("over");isCookie&&(isClick=!0,$("#over").remove())
```

**Comment by uBlock-user** [comment]
No, it's fixed via exception filter of `ads.watch.js` in Easylist.

**Comment by ghajini** [comment]
Nothing to do with that exception filter...
This script line is responsible

`</script><script type=text/javascript>function setCookie(e,t,n){var o=new Date;o.setTime(o.getTime()+n);var r="expires="+o.toUTCString();document.cookie=e+"="+t+";"+r+";path=/"}function getCookie(e){for(var t=e+"=",n=document.cookie.split(";"),o=0;o<n.length;o++){for(var r=n[o];" "==r.charAt(0);)r=r.substring(1);if(0==r.indexOf(t))return r.substring(t.length,r.length)}return""}var isClick=!1,msgWebmaster='<center style="background:#00000054;margin:auto;width:100%;border-radius:0 0 5px 5px;padding:15px">\n            <h1>Hello Webmaster</h1>\n            <br/>\n            <h3>Please <span style="color:red">REMOVE SANDBOX</span> attribute <span style="color:red">IN IFRAME</span></h3>\n            <br/><br/>\n            <h1>Dear Visitor</h1>\n            <br/>\n            <h3>Please <span style="color:red">DISABLE ADBLOCK</span> extension or <span style="color:red">ALLOW POPUNDER</span> for this site.</h3>\n            <br/>\n            <h3>Video can\'t play if this page not show popunder.</h3>\n            <br/>\n            <h4>Thank you.</h4>\n        </center>',styleWebmaster="width:100%;height:100% !important;background: url(https://iamcdn.net/img/block-pop.jpg) center center no-repeat;background-size:contain;position:absolute",styleMinion="width:100%;height:100% !important;background: url(https://iamcdn.net/img/block.jpg) center center no-repeat;background-size:contain;position:absolute";$(document).ready(function(){$("#over").click(function(){html2canvas($("#player"),{onrendered:function(e){isClick=!0;var t=e.toDataURL("image/png"),n=window.open(t);n?($("#over").remove(),setCookie("over",!0,36e5)):("undefined"!=typeof jwplayer&&jwplayer&&jwplayer().remove(),$("#player").css("cssText",styleWebmaster).html(msgWebmaster)),n.focus(),n.close()}})}),setTimeout(function(){try{"undefined"!=typeof ADS&&"undefined"!=typeof html2canvas||$("#player").css("cssText",styleMinion).html("")}catch(e){$("#player").css("cssText",styleMinion).html("")}},5e3),setTimeout(function(){isClick||("undefined"!=typeof jwplayer&&jwplayer&&jwplayer().remove(),$("#player").css("cssText",styleWebmaster).html(msgWebmaster))},3e4)});var isCookie=getCookie("over");isCookie&&(isClick=!0,$("#over").remove())`

How to defuse this

I have done this with 
`hydrax.net##+js(aopr, isClick)` it works
Is it correct scriptlet progammatically?

**Comment by uBlock-user** [comment]
> Nothing to do with that exception filter...

I disagree, it has everything to do with that, if I block that script, I can reproduce the anti-adblock notice.

> Is it correct scriptlet progammatically?

You're disabling execution of the script **mid-way**, so it doesn't matter whether it is correct or not, but you will have to unbreak whatever breakage accompanies as a side-effect with that filter.

**Comment by ghajini** [comment]
> >  **mid-way**
>
>what the correct way/filter to disable that script then?

**Comment by uBlock-user** [comment]
Whichever way works without causing breakage with site functionality.
