### ISSUE TITLE
Q & A

### ISSUE THREAD

**Issue by ghajini** [uBlock-user/uBO-Personal-Filters#13]
Anything can be done for this

https://www.reddit.com/r/uBlockOrigin/comments/i13gkj/soralink_defuserbypass/

Most preferrably on many movies sites

A userscript or else?

**Comment by uBlock-user** [comment]
Final destination link is not hard-coded, so not possible.

Instead of downloading torrents for such scummy sites, why don't you use torrentz2.is, the search engine itself ? 

https://torrentz2.is/search?f=Cursed+s01+Dual+Audio
