### ISSUE TITLE
burn after reading

### ISSUE THREAD

**Issue by bogachenko** [uBlock-user/uBO-Personal-Filters#5]
Hello, anime
I have a question. You have this rule.

`||youtube.com^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' blob: data: *.ggpht.com *.googlevideo.com *.ytimg.com *.googleusercontent.com www.youtube.com`

This rule downloads only those addresses that are written here on YouTube. And does not give permission to download any scum type `doubleclick.net`. He is not in the logger on youtube. Great. But why does it appear on third-party sites (eg. `grantthornton.pl`) where youtube is used. It is blocked, there are no questions, but why is it displayed when (seems) it should not?
![Opera Снимок_2019-05-29_153826_cgbcahbpdhpcegmbfconppldiemgcoii](https://user-images.githubusercontent.com/8535285/58530177-7a61a380-8229-11e9-88f3-7fb194132882.png)

**Comment by uBlock-user** [comment]
> But why does it appear on third-party sites (eg. grantthornton.pl

because there's a youtube embedded video linked on that site ? Thought this was obvious.

**Comment by bogachenko** [comment]
question about, why csp rule on the main site shows in the logger one result (without scam site `doubleclick.net`), and in third-party another result.

do I need to write csp for third-party sites separately?  why not show the same output?

**Comment by uBlock-user** [comment]
> why csp rule on the main site shows in the logger one result (without scam site doubleclick.net), and in third-party another result.

Youtube is [embedded](https://i.gyazo.com/6b0a10d0261cc1ef31b25af542cad54d.jpg), it's not the main site. What's the problem ?

> do I need to write csp for third-party sites separately? 

No.

> why not show the same output?

What same output ?

**Comment by bogachenko** [comment]
>Youtube is embedded, it's not the main site. What's the problem ?

There is no problem, doubleclick.net is blocked. The question is why it is displayed in the logger on third-party sites (On Youtube is embedded)? It's all.

**Comment by uBlock-user** [comment]
>  why it is displayed in the logger on third-party sites

It's displayed everywhere since https://github.com/uBlockOrigin/uBlock-issues/issues/552

**Comment by bogachenko** [comment]
And the last question (back to the beginning) so that doubleclick.net (or any other site) does not appear on third-party sites, do I need to create separate rules for these sites?

**Comment by bogachenko** [comment]
anime-buddy please dont ignore me. the last question/and i will leave

**Comment by uBlock-user** [comment]
> so that doubleclick.net (or any other site) does not appear on third-party sites (with the current version of the extension), do I need to create separate rules for these sites?

I already said no. It only appears in the logger because gorhill added that enhancement.

> anime-buddy please dont ignore me

I was offline.
