### ISSUE TITLE
nani?

### ISSUE THREAD

**Issue by bogachenko** [uBlock-user/uBO-Personal-Filters#6]
`||scorecardresearch.com^$important` x2
`outlook.live.com##a[href^="http://www.myfreecams.com/"]`unnecessary, coz u have `outlook.live.com##a[href^="http://"]`
Anime, I do not want to create fork. Remove duplicates by yourself

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Personal-Filters/commit/656a1829fa1ae5ad7e508c58d542fc653f8181dc
https://github.com/uBlock-user/uBO-Personal-Filters/commit/5615489af9f3667175a251f153367d464c97feb8

**Comment by bogachenko** [comment]
change it `||luxubu.review^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' fvs.io *.leasewebcdn.me` to 
`||luxubu.review^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' fvs.io *.leasewebcdn.me *.hlsmp4.com`


or you can use my csp


`||luxubu.review^$csp=script-src 'self' *.gstatic.com *.luxubu.review; media-src *.hlsmp4.com fvs.io`



***
By the way, what is it and why?
*.leasewebcdn.me

**Comment by uBlock-user** [comment]
> change it ||luxubu.review^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' fvs.io *.leasewebcdn.me to
||luxubu.review^$csp=default-src 'self' 'unsafe-inline' 'unsafe-eval' fvs.io *.leasewebcdn.me *.hlsmp4.com

There's no such filter in my list.

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Personal-Filters/commit/4d472758cb5b5f1b0a3952c912c1b26b881c41a0

**Comment by bogachenko** [comment]
add to `bmovies.*^$csp=` still and this `*.cloudcdnvideo.com`

**Comment by uBlock-user** [comment]
> add to bmovies.*^$csp= still and this *.cloudcdnvideo.com
> test https://bmovies.video/online/my-dinner-with-herve/1z6An

> add to putlockertv.*^$csp= still and this entervideo.net and remove ;upgrade-insecure-requests

> test http://putlockertv.ws/watch/kvXB1LwG-men-in-black-international.html


Both are fake websites, real domain for putlockertv is `https://www6.putlockertv.to/`, bmovies is owned by fmovies, so use that. bmovies was the backup domain for fmovies when it was seized by the registrar.

> ||pornhub.*^$csp=

does pornhub have mirrors?

Yes, `pornhub.net`

> add to kissanime.ru^$csp= still and this *.novelplanet.me
BTW I have popups https://witalfieldt.com/redirect?tid=782297&ref= its on kissanime.ru, not on novelplanet.me

I will need to check if it happens on novelplanet or on kissanime first.

**Comment by bogachenko** [comment]
> ||pornhub.*^$csp=
does pornhub have mirrors?
Yes, pornhub.net

its redirect-site. not mirror

**Comment by uBlock-user** [comment]
> its redirect-site. not mirror
I'm not getting redirected.

**Comment by bogachenko** [comment]
eh.. what?

**Comment by uBlock-user** [comment]
https://github.com/uBlock-user/uBO-Personal-Filters/commit/34d3f20c7b69ddee3d022478d241da712243cc62

> eh.. what?

https://i.gyazo.com/bd0bf8391a9062c632b54293a6bca641.png
